name: SmartLead Daily Automation

on:
  schedule:
    # NOTE: Runs at 7:00 AM UTC on weekdays (Mon-Fri).
    - cron: '0 7 * * 1-5'
  
  workflow_dispatch:

jobs:
  run-scheduler:
    runs-on: ubuntu-latest

    defaults:
      run:
        # CORRECTED: This is the path INSIDE your repository.
        # It is relative to the checkout root.
        working-directory: ./SmartLead Daily Automation/Automation

    env:
      SMARTLEAD_API_KEY: ${{ secrets.SMARTLEAD_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          # CORRECTED: The hashFiles path must also be the path from the repo root.
          key: ${{ runner.os }}-pip-${{ hashFiles('Seamless-Source---Marketing/SmartLead Daily Automation/Automation/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        # This will now correctly run inside the 'Automation' folder.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Automation Script
        run: python automation.py
